[build]
  publish = "frontend/build"
  command = "cd frontend && npm ci --silent && npm run build"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_FLAGS = "--silent"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
